In [15]:
!pip install mwclient
import mwclient
site = mwclient.Site("en.wikipedia.org")
page = site.Pages['Ethereum']

Requirement already satisfied: mwclient in /usr/local/lib/python3.11/dist-packages (0.11.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.11/dist-packages (from mwclient) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib->mwclient) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib->mwclient) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (2025.1.31)

In [16]:
revs = list(page.revisions())
revs[0]

OrderedDict([('revid', 1282875834),
             ('parentid', 1282478024),
             ('minor', ''),
             ('user', 'Learningman00'),
             ('timestamp',
              time.struct_time(tm_year=2025, tm_mon=3, tm_mday=29, tm_hour=4, tm_min=25, tm_sec=33, tm_wday=5, tm_yday=88, tm_isdst=-1)),
             ('comment',
              '/* The Merge: Transition from Proof-of-Work to Proof-of-Stake */')])

In [17]:
revs = sorted(revs,key=lambda revs:revs['timestamp'])
revs[0]['timestamp']

time.struct_time(tm_year=2014, tm_mon=1, tm_mday=27, tm_hour=1, tm_min=53, tm_sec=45, tm_wday=0, tm_yday=27, tm_isdst=-1)

In [18]:
len(revs)

3832

In [19]:
# first revision was made in this date

import time
df_time = time.strftime("%Y-%m-%d",revs[0]['timestamp'])
df_time

'2014-01-27'

In [20]:
#making  a transformer pipeline for sentiment analysis
from transformers import pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

def sentiment_revs(text):
  sentiment = sentiment_pipeline([text[:250]])[0]
  # return sentiment
  score = sentiment['score']
  if sentiment['label'] == "NEGATIVE":
    score*=-1
  return score
sentiment_revs("hello ayush")

#why we used [0] because it will give the first list of score because huggingface give a list of scores

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu

0.999355137348175

In [21]:
#now we will loop over the revs
edits = {}

for rev in revs:
  date = time.strftime("%Y-%m-%d",rev['timestamp'])
  if date not in edits:
    edits[date] = dict(curr_sent=list(),edit_count=0)

  edits[date]['edit_count'] += 1

  comment = rev.get("comment","")
  edits[date]['curr_sent'].append(sentiment_revs(comment))

In [22]:
from statistics import mean

for keys in edits:
  if len(edits[keys]['curr_sent'])> 0:
    edits[keys]['mean_sentiments'] = mean(edits[keys]['curr_sent'])
    edits[keys]["neg_sentiments"] = len([s for s in edits[keys]['curr_sent'] if s < 0]) / len(edits[keys]['curr_sent'])
    edits[keys]["pos_sentiments"] = len([s for s in edits[keys]['curr_sent'] if s > 0]) / len(edits[keys]['curr_sent'])

  else:
    edits[keys]['mean_sentiments'] = 0
    edits[keys]['neg_sentiments'] = 0
    edits[keys]['pos_sentiments'] = 0
  del edits[keys]['curr_sent']
edits

{'2014-01-27': {'edit_count': 1,
  'mean_sentiments': -0.9985105395317078,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-02-01': {'edit_count': 1,
  'mean_sentiments': -0.997276246547699,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-04-06': {'edit_count': 5,
  'mean_sentiments': 0.7909793376922607,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-04-09': {'edit_count': 24,
  'mean_sentiments': 0.6464069038629532,
  'neg_sentiments': 0.08333333333333333,
  'pos_sentiments': 0.9166666666666666},
 '2014-04-10': {'edit_count': 9,
  'mean_sentiments': -0.3615177207522922,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2014-04-11': {'edit_count': 10,
  'mean_sentiments': 0.5150125801563263,
  'neg_sentiments': 0.2,
  'pos_sentiments': 0.8},
 '2014-04-12': {'edit_count': 2,
  'mean_sentiments': -0.04391053318977356,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2014-04-13': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-04-17': {'edit_count': 9,
  'mean_sentiments': 0.30852222442626953,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2014-04-18': {'edit_count': 1,
  'mean_sentiments': 0.9109594821929932,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-04-24': {'edit_count': 2,
  'mean_sentiments': 0.9975883960723877,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-04-28': {'edit_count': 1,
  'mean_sentiments': -0.936257541179657,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-06-01': {'edit_count': 1,
  'mean_sentiments': 0.9758297204971313,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-06-10': {'edit_count': 1,
  'mean_sentiments': 0.999515175819397,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-06-29': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-07-01': {'edit_count': 1,
  'mean_sentiments': 0.872576117515564,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-07-27': {'edit_count': 1,
  'mean_sentiments': 0.9975883960723877,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-07-28': {'edit_count': 7,
  'mean_sentiments': 0.0981013434273856,
  'neg_sentiments': 0.42857142857142855,
  'pos_sentiments': 0.5714285714285714},
 '2014-07-29': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-08-03': {'edit_count': 1,
  'mean_sentiments': -0.9881350994110107,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-08-06': {'edit_count': 1,
  'mean_sentiments': -0.8130702376365662,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-08-10': {'edit_count': 3,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-08-11': {'edit_count': 4,
  'mean_sentiments': 0.4119809716939926,
  'neg_sentiments': 0.25,
  'pos_sentiments': 0.75},
 '2014-08-12': {'edit_count': 3,
  'mean_sentiments': -0.4160490234692891,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2014-08-14': {'edit_count': 2,
  'mean_sentiments': -0.9828210473060608,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-08-24': {'edit_count': 1,
  'mean_sentiments': 0.994047999382019,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-08-27': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-09-03': {'edit_count': 10,
  'mean_sentiments': 0.5592141032218934,
  'neg_sentiments': 0.2,
  'pos_sentiments': 0.8},
 '2014-09-04': {'edit_count': 3,
  'mean_sentiments': 0.24925305445988974,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2014-09-08': {'edit_count': 1,
  'mean_sentiments': -0.9565961956977844,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-09-30': {'edit_count': 1,
  'mean_sentiments': 0.9787663221359253,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-10-08': {'edit_count': 2,
  'mean_sentiments': 0.8621626198291779,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-10-14': {'edit_count': 2,
  'mean_sentiments': -0.00965312123298645,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2014-10-23': {'edit_count': 4,
  'mean_sentiments': -0.0022448748350143433,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2014-11-13': {'edit_count': 1,
  'mean_sentiments': 0.9975883960723877,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-11-23': {'edit_count': 1,
  'mean_sentiments': 0.9984303116798401,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-12-08': {'edit_count': 5,
  'mean_sentiments': 0.8743553996086121,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-12-14': {'edit_count': 1,
  'mean_sentiments': 0.9300209879875183,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2014-12-17': {'edit_count': 1,
  'mean_sentiments': -0.9702252149581909,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-12-19': {'edit_count': 8,
  'mean_sentiments': 0.6857524961233139,
  'neg_sentiments': 0.125,
  'pos_sentiments': 0.875},
 '2014-12-20': {'edit_count': 1,
  'mean_sentiments': -0.9990710020065308,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-12-23': {'edit_count': 1,
  'mean_sentiments': -0.9980879426002502,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2014-12-27': {'edit_count': 2,
  'mean_sentiments': -0.0004969239234924316,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-01-05': {'edit_count': 1,
  'mean_sentiments': -0.9986577033996582,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-01-10': {'edit_count': 2,
  'mean_sentiments': 0.9256414473056793,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-01-15': {'edit_count': 4,
  'mean_sentiments': 0.7814871519804001,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-01-16': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-01-26': {'edit_count': 1,
  'mean_sentiments': 0.9109594821929932,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-01-30': {'edit_count': 1,
  'mean_sentiments': 0.9929959177970886,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-02-04': {'edit_count': 1,
  'mean_sentiments': 0.842860996723175,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-02-12': {'edit_count': 1,
  'mean_sentiments': 0.8548060059547424,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-02-13': {'edit_count': 1,
  'mean_sentiments': -0.840632438659668,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-02-16': {'edit_count': 3,
  'mean_sentiments': -0.8955996632575989,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-02-17': {'edit_count': 1,
  'mean_sentiments': -0.979144275188446,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-02-19': {'edit_count': 3,
  'mean_sentiments': -0.4154775142669678,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2015-02-20': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-02-21': {'edit_count': 2,
  'mean_sentiments': -0.9989575445652008,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-03-18': {'edit_count': 1,
  'mean_sentiments': 0.9975903034210205,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-03-21': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-03-22': {'edit_count': 1,
  'mean_sentiments': -0.9968094229698181,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-03-26': {'edit_count': 1,
  'mean_sentiments': -0.9994649291038513,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-03-31': {'edit_count': 3,
  'mean_sentiments': -0.28288282950719196,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2015-04-09': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-04-20': {'edit_count': 1,
  'mean_sentiments': 0.9435798525810242,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-04-24': {'edit_count': 2,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-05-09': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-05-17': {'edit_count': 1,
  'mean_sentiments': 0.8466593027114868,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-05-24': {'edit_count': 1,
  'mean_sentiments': 0.996212363243103,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-05-26': {'edit_count': 1,
  'mean_sentiments': 0.9866401553153992,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-05-30': {'edit_count': 1,
  'mean_sentiments': 0.9959832429885864,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-06-08': {'edit_count': 1,
  'mean_sentiments': 0.977993905544281,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-06-26': {'edit_count': 2,
  'mean_sentiments': 0.008801639080047607,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-07-18': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-07-22': {'edit_count': 1,
  'mean_sentiments': -0.8920957446098328,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-07-23': {'edit_count': 1,
  'mean_sentiments': 0.9354426264762878,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-07-25': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-07-26': {'edit_count': 2,
  'mean_sentiments': -0.9177615344524384,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-07-27': {'edit_count': 1,
  'mean_sentiments': -0.9994345307350159,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-07-29': {'edit_count': 3,
  'mean_sentiments': -0.4103458523750305,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2015-07-30': {'edit_count': 6,
  'mean_sentiments': 0.30065661668777466,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2015-07-31': {'edit_count': 2,
  'mean_sentiments': 0.8435935080051422,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-01': {'edit_count': 2,
  'mean_sentiments': -0.00036767125129699707,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-08-02': {'edit_count': 2,
  'mean_sentiments': -0.07246798276901245,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-08-04': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-05': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-06': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-07': {'edit_count': 2,
  'mean_sentiments': 0.7570407390594482,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-09': {'edit_count': 6,
  'mean_sentiments': -0.6508857409159342,
  'neg_sentiments': 0.8333333333333334,
  'pos_sentiments': 0.16666666666666666},
 '2015-08-10': {'edit_count': 7,
  'mean_sentiments': -0.4280558228492737,
  'neg_sentiments': 0.7142857142857143,
  'pos_sentiments': 0.2857142857142857},
 '2015-08-13': {'edit_count': 1,
  'mean_sentiments': 0.8661127686500549,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-14': {'edit_count': 2,
  'mean_sentiments': -0.12547701597213745,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-08-21': {'edit_count': 1,
  'mean_sentiments': 0.9972445964813232,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-22': {'edit_count': 1,
  'mean_sentiments': -0.9982075691223145,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-08-28': {'edit_count': 2,
  'mean_sentiments': 0.9710939228534698,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-08-30': {'edit_count': 1,
  'mean_sentiments': -0.9667150378227234,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-09-07': {'edit_count': 5,
  'mean_sentiments': -0.9685040235519409,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-09-13': {'edit_count': 1,
  'mean_sentiments': -0.996834933757782,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-09-18': {'edit_count': 1,
  'mean_sentiments': 0.9749864339828491,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-09-20': {'edit_count': 1,
  'mean_sentiments': -0.9939032196998596,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-09-22': {'edit_count': 1,
  'mean_sentiments': 0.9972445964813232,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-09-23': {'edit_count': 2,
  'mean_sentiments': -0.1256546676158905,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-09-24': {'edit_count': 1,
  'mean_sentiments': -0.9962469935417175,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-09-25': {'edit_count': 1,
  'mean_sentiments': 0.9749864339828491,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-09-28': {'edit_count': 1,
  'mean_sentiments': 0.977993905544281,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-09-29': {'edit_count': 4,
  'mean_sentiments': -0.4756421446800232,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2015-09-30': {'edit_count': 1,
  'mean_sentiments': 0.9918097853660583,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-10-03': {'edit_count': 4,
  'mean_sentiments': 0.42909204959869385,
  'neg_sentiments': 0.25,
  'pos_sentiments': 0.75},
 '2015-10-13': {'edit_count': 2,
  'mean_sentiments': -0.9952731728553772,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-10-22': {'edit_count': 2,
  'mean_sentiments': -0.028130769729614258,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-11-05': {'edit_count': 2,
  'mean_sentiments': 0.916404664516449,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-11-06': {'edit_count': 8,
  'mean_sentiments': -0.06382669508457184,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-11-13': {'edit_count': 1,
  'mean_sentiments': -0.9893608689308167,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-11-20': {'edit_count': 3,
  'mean_sentiments': 0.2425894339879354,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2015-11-24': {'edit_count': 1,
  'mean_sentiments': 0.7481207847595215,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-11-26': {'edit_count': 3,
  'mean_sentiments': -0.993152936299642,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-11-30': {'edit_count': 15,
  'mean_sentiments': 0.01151731014251709,
  'neg_sentiments': 0.4666666666666667,
  'pos_sentiments': 0.5333333333333333},
 '2015-12-11': {'edit_count': 3,
  'mean_sentiments': -0.2990707556406657,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2015-12-16': {'edit_count': 1,
  'mean_sentiments': 0.9107905030250549,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-12-18': {'edit_count': 3,
  'mean_sentiments': -0.9945226907730103,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2015-12-19': {'edit_count': 4,
  'mean_sentiments': -0.11695535480976105,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2015-12-27': {'edit_count': 2,
  'mean_sentiments': 0.9926086962223053,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2015-12-28': {'edit_count': 6,
  'mean_sentiments': -0.23435727755228677,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2016-01-09': {'edit_count': 1,
  'mean_sentiments': -0.8130702376365662,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-01-16': {'edit_count': 4,
  'mean_sentiments': -0.5624943524599075,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2016-01-17': {'edit_count': 1,
  'mean_sentiments': -0.9994869232177734,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-01-28': {'edit_count': 2,
  'mean_sentiments': -0.03347301483154297,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2016-02-04': {'edit_count': 2,
  'mean_sentiments': -0.03454619646072388,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2016-02-08': {'edit_count': 2,
  'mean_sentiments': -0.12441903352737427,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2016-02-10': {'edit_count': 1,
  'mean_sentiments': -0.9975160360336304,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-02-16': {'edit_count': 2,
  'mean_sentiments': -0.986951619386673,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-02-17': {'edit_count': 13,
  'mean_sentiments': -0.3891305144016559,
  'neg_sentiments': 0.6923076923076923,
  'pos_sentiments': 0.3076923076923077},
 '2016-02-19': {'edit_count': 4,
  'mean_sentiments': -0.5958839505910873,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2016-02-20': {'edit_count': 12,
  'mean_sentiments': -0.8251775205135345,
  'neg_sentiments': 0.9166666666666666,
  'pos_sentiments': 0.08333333333333333},
 '2016-02-21': {'edit_count': 3,
  'mean_sentiments': -0.9442015290260315,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-02-22': {'edit_count': 4,
  'mean_sentiments': 0.4315732270479202,
  'neg_sentiments': 0.25,
  'pos_sentiments': 0.75},
 '2016-02-23': {'edit_count': 15,
  'mean_sentiments': -0.356895383199056,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2016-02-24': {'edit_count': 2,
  'mean_sentiments': -0.9991590976715088,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-02-25': {'edit_count': 2,
  'mean_sentiments': -0.12582620978355408,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2016-02-26': {'edit_count': 3,
  'mean_sentiments': -0.295643945535024,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2016-02-28': {'edit_count': 2,
  'mean_sentiments': 0.04569658637046814,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2016-03-02': {'edit_count': 4,
  'mean_sentiments': 0.31192488968372345,
  'neg_sentiments': 0.25,
  'pos_sentiments': 0.75},
 '2016-03-03': {'edit_count': 2,
  'mean_sentiments': 0.9779015779495239,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2016-03-04': {'edit_count': 1,
  'mean_sentiments': -0.999438464641571,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-03-05': {'edit_count': 7,
  'mean_sentiments': 0.49891904422215055,
  'neg_sentiments': 0.14285714285714285,
  'pos_sentiments': 0.8571428571428571},
 '2016-03-08': {'edit_count': 1,
  'mean_sentiments': 0.9624135494232178,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2016-03-11': {'edit_count': 3,
  'mean_sentiments': -0.2921069264411926,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2016-03-13': {'edit_count': 5,
  'mean_sentiments': 0.16214537620544434,
  'neg_sentiments': 0.4,
  'pos_sentiments': 0.6},
 '2016-03-14': {'edit_count': 1,
  'mean_sentiments': -0.991378664970398,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-03-16': {'edit_count': 2,
  'mean_sentiments': -0.9629538655281067,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-03-18': {'edit_count': 1,
  'mean_sentiments': -0.9918463826179504,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2016-03-20': {'edit_count': 21,
  'mean_sentiments': -0.5020367247717721,
  'neg_sentiments': 0.7619047619047619,
  'pos_sentiments': 0.23809523809523808},
 '2016-03-21': {'edit_count': 40,
  'mean_sentiments': -0.3694640606641769,
  'neg_sentiments': 0.675,
  'pos_sentiments': 0.325},
 '2016-03-22': {'edit_count': 10,
  'mean_sentiments': -0.5923540592193604,
  'neg_sentiments': 0.8,
  'pos_sentiments': 0.2},
 '2016-03-23': {'edit_count': 10,

In [27]:
import pandas as pd
df_sent_eth = pd.DataFrame.from_dict(edits,orient='index')
df_sent_eth.index = pd.to_datetime(df_sent_eth.index)
df_sent_eth

            edit_count  mean_sentiments  neg_sentiments  pos_sentiments
2014-01-27           1        -0.998511        1.000000        0.000000
2014-02-01           1        -0.997276        1.000000        0.000000
2014-04-06           5         0.790979        0.000000        1.000000
2014-04-09          24         0.646407        0.083333        0.916667
2014-04-10           9        -0.361518        0.666667        0.333333
...                ...              ...             ...             ...
2025-03-10           1         0.977994        0.000000        1.000000
2025-03-18           7        -0.485668        0.714286        0.285714
2025-03-21           4        -0.466895        0.750000        0.250000
2025-03-26           3        -0.334291        0.666667        0.333333
2025-03-29           1         0.996167        0.000000        1.000000

[1199 rows x 4 columns]

In [28]:
from datetime import datetime
date = pd.date_range(start='2014-01-27',end=datetime.today())
df_sent_eth = df_sent_eth.reindex(date,fill_value=0)
df_sent_eth

            edit_count  mean_sentiments  neg_sentiments  pos_sentiments
2014-01-27           1        -0.998511             1.0             0.0
2014-01-28           0         0.000000             0.0             0.0
2014-01-29           0         0.000000             0.0             0.0
2014-01-30           0         0.000000             0.0             0.0
2014-01-31           0         0.000000             0.0             0.0
...                ...              ...             ...             ...
2025-03-27           0         0.000000             0.0             0.0
2025-03-28           0         0.000000             0.0             0.0
2025-03-29           1         0.996167             0.0             1.0
2025-03-30           0         0.000000             0.0             0.0
2025-03-31           0         0.000000             0.0             0.0

[4082 rows x 4 columns]

In [29]:
df_sent_eth_roll = df_sent_eth.rolling(30, min_periods=30).mean()
df_sent_eth_roll = df_sent_eth_roll.dropna()
df_sent_eth_roll

            edit_count  mean_sentiments  neg_sentiments  pos_sentiments
2014-02-25    0.066667        -0.066526        0.066667        0.000000
2014-02-26    0.033333        -0.033243        0.033333        0.000000
2014-02-27    0.033333        -0.033243        0.033333        0.000000
2014-02-28    0.033333        -0.033243        0.033333        0.000000
2014-03-01    0.033333        -0.033243        0.033333        0.000000
...                ...              ...             ...             ...
2025-03-27    0.533333         0.014642        0.071032        0.095635
2025-03-28    0.533333         0.014642        0.071032        0.095635
2025-03-29    0.566667         0.047848        0.071032        0.128968
2025-03-30    0.533333         0.022910        0.071032        0.095635
2025-03-31    0.533333         0.022910        0.071032        0.095635

[4053 rows x 4 columns]

In [30]:
df_sent_eth_roll.to_csv("df_sent_eth_roll.csv")

In [31]:
len(df_sent_eth_roll)

4053