In [1]:
!pip install mwclient
import mwclient
site = mwclient.Site('en.wikipedia.org')
page = site.pages['Bitcoin']
page

Collecting mwclient
  Downloading mwclient-0.11.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.11/dist-packages (from mwclient) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib->mwclient) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib->mwclient) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib->mwclient) (2025.1.31)
Downloading mwclient-0.11.0-py3-none-any.whl (33 kB)
Installing collected packages: mwclient
Successfully installed mwclient-0.11.0

In [2]:
revs = list(page.revisions())

In [3]:
revs[0]

OrderedDict([('revid', 1281323903),
             ('parentid', 1280330283),
             ('minor', ''),
             ('user', 'Davide King'),
             ('timestamp',
              time.struct_time(tm_year=2025, tm_mon=3, tm_mday=19, tm_hour=17, tm_min=46, tm_sec=48, tm_wday=2, tm_yday=78, tm_isdst=-1)),
             ('comment', '/* 2020–present */ copyedit')])

In [4]:
revs = sorted(revs,key=lambda revs:revs['timestamp'])

In [5]:
revs[0]
# revs[0]['timestamp']

OrderedDict([('revid', 275832581),
             ('parentid', 0),
             ('user', 'Pratyeka'),
             ('timestamp',
              time.struct_time(tm_year=2009, tm_mon=3, tm_mday=8, tm_hour=16, tm_min=41, tm_sec=7, tm_wday=6, tm_yday=67, tm_isdst=-1)),
             ('comment', 'creation (stub)')])

In [6]:
len(revs)

17984

In [7]:
from transformers import pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# result = sentiment_pipeline(["I love this product!"])
# print(result)

def find_sentiment(text):
    sent = sentiment_pipeline([text[:250]])[0]
    score = sent["score"]
    if sent["label"] == "NEGATIVE":
        score *= -1
    return score

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu

Why Use [0]?
Since the result is a list with one element, we need to extract the first element to access the dictionary inside.


```
sent = sentiment_pipeline(["I love this product!"])[0]  # Extract the first element
print(sent)

{'label': 'POSITIVE', 'score': 0.9998}
```


Now, we have only the dictionary instead of a list.

In [8]:
find_sentiment("i lavis you")

-0.8655312061309814

just for measuring metrics evaltion

```
from sklearn.metrics import r2_score
texts = [
    "I love this product!",       # Expected sentiment: 0.9 (Very positive)
    "This is a terrible service!", # Expected sentiment: -0.8 (Very negative)
    "It's okay, not great.",       # Expected sentiment: 0.2 (Neutral)
    "Absolutely fantastic!",       # Expected sentiment: 1.0 (Highly positive)
    "Worst experience ever."       # Expected sentiment: -1.0 (Highly negative)
]

actual_score = [0.9, -0.8, 0.2, 1.0, -1.0]
predicted_score = [find_sentiment(text) for text in texts]

r2 = r2_score(actual_score,predicted_score)
print("Actual Scores:   ", actual_score)
print("Predicted Scores:", predicted_score)
print("R² Score:        ", r2)
```
the score coming is 0.5

In [9]:
import time
edits = {}

for rev in revs:
    date = time.strftime("%Y-%m-%d", rev["timestamp"])
    if date not in edits:
        edits[date] = dict(sentiments=list(), edit_count=0)

    edits[date]["edit_count"] += 1

    comment = rev.get("comment", "")
    edits[date]["sentiments"].append(find_sentiment(comment))
edits

{'2009-03-08': {'sentiments': [-0.9905919432640076,
   0.7481208443641663,
   -0.9907428622245789,
   -0.9688863158226013],
  'edit_count': 4},
 '2009-08-05': {'sentiments': [0.7481208443641663], 'edit_count': 1},
 '2009-08-06': {'sentiments': [0.9957457184791565, 0.9957457184791565],
  'edit_count': 2},
 '2009-08-14': {'sentiments': [0.930020809173584], 'edit_count': 1},
 '2009-10-13': {'sentiments': [0.5404348969459534, -0.9954361319541931],
  'edit_count': 2},
 '2009-11-18': {'sentiments': [0.8839507699012756], 'edit_count': 1},
 '2009-12-08': {'sentiments': [-0.9869275689125061], 'edit_count': 1},
 '2009-12-17': {'sentiments': [-0.9975171089172363], 'edit_count': 1},
 '2010-02-23': {'sentiments': [-0.9994946718215942], 'edit_count': 1},
 '2010-03-18': {'sentiments': [0.875877320766449], 'edit_count': 1},
 '2010-04-13': {'sentiments': [0.930020809173584,
   0.815800666809082,
   0.815800666809082,
   0.815800666809082],
  'edit_count': 4},
 '2010-04-15': {'sentiments': [0.930020809173584,
   0.7481208443641663,
   0.7481208443641663,
   0.7481208443641663,
   0.815800666809082,
   0.815800666809082,
   -0.9969743490219116,
   0.815800666809082],
  'edit_count': 8},
 '2010-04-28': {'sentiments': [0.7481208443641663, -0.9900070428848267],
  'edit_count': 2},
 '2010-05-13': {'sentiments': [-0.9664837121963501], 'edit_count': 1},
 '2010-06-17': {'sentiments': [0.9957457184791565, 0.9957457184791565],
  'edit_count': 2},
 '2010-06-18': {'sentiments': [0.6754596829414368,
   0.9875591397285461,
   0.9875591397285461,
   0.9875591397285461,
   0.9875591397285461,
   0.9875591397285461,
   -0.8274527192115784,
   -0.6475812196731567,
   -0.9079524278640747],
  'edit_count': 9},
 '2010-06-19': {'sentiments': [0.9875591397285461], 'edit_count': 1},
 '2010-06-20': {'sentiments': [0.9875591397285461,
   0.9875591397285461,
   0.930020809173584],
  'edit_count': 3},
 '2010-06-21': {'sentiments': [0.7481208443641663,
   0.7481208443641663,
   -0.9935784339904785,
   0.9360668659210205,
   0.9360668659210205,
   0.9996433258056641,
   0.9360668659210205],
  'edit_count': 7},
 '2010-06-23': {'sentiments': [0.9360668659210205,
   0.815800666809082,
   0.815800666809082,
   0.8521847128868103],
  'edit_count': 4},
 '2010-06-28': {'sentiments': [0.7481208443641663,
   0.7481208443641663,
   -0.9898198246955872,
   0.6262343525886536],
  'edit_count': 4},
 '2010-06-29': {'sentiments': [0.7481208443641663], 'edit_count': 1},
 '2010-07-05': {'sentiments': [0.9360668659210205], 'edit_count': 1},
 '2010-07-07': {'sentiments': [-0.9996860027313232, 0.6941722631454468],
  'edit_count': 2},
 '2010-07-08': {'sentiments': [0.9991004467010498, -0.9610505700111389],
  'edit_count': 2},
 '2010-07-09': {'sentiments': [-0.9049850702285767], 'edit_count': 1},
 '2010-07-11': {'sentiments': [0.6584407687187195,
   0.7481208443641663,
   -0.783947229385376,
   -0.9954730868339539,
   0.9856441020965576,
   -0.7345219850540161,
   0.9975513815879822,
   0.8681235909461975,
   0.7481208443641663,
   0.998762845993042,
   0.7481208443641663,
   0.9356325268745422,
   -0.9994708895683289],
  'edit_count': 13},
 '2010-07-12': {'sentiments': [-0.9998044371604919,
   0.9995076656341553,
   -0.9989984631538391,
   -0.9980356097221375,
   0.9592856764793396,
   -0.70451819896698,
   -0.9898375272750854,
   -0.8494006991386414,
   0.9916039109230042],
  'edit_count': 9},
 '2010-07-13': {'sentiments': [0.7481208443641663,
   0.7481208443641663,
   0.9817115068435669,
   0.7481208443641663],
  'edit_count': 4},
 '2010-07-14': {'sentiments': [-0.9994907379150391,
   0.7481208443641663,
   -0.9707220196723938,
   0.978839099407196],
  'edit_count': 4},
 '2010-07-15': {'sentiments': [-0.9955335855484009,
   -0.9700435996055603,
   -0.9997710585594177,
   -0.6143912672996521],
  'edit_count': 4},
 '2010-07-16': {'sentiments': [0.9878523349761963,
   0.9716765284538269,
   0.9957457184791565,
   0.9957457184791565,
   0.8669613599777222,
   0.8669613599777222],
  'edit_count': 6},
 '2010-07-18': {'sentiments': [0.6105569005012512, -0.9916438460350037],
  'edit_count': 2},
 '2010-07-19': {'sentiments': [0.8669613599777222,
   0.930020809173584,
   0.930020809173584,
   0.7481208443641663],
  'edit_count': 4},
 '2010-07-21': {'sentiments': [-0.9986214637756348,
   0.9901739358901978,
   -0.999261200428009,
   0.9895368814468384,
   -0.9997262358665466,
   0.7481208443641663,
   0.8669613599777222,
   -0.9913643598556519,
   -0.998372495174408,
   -0.9962494969367981,
   -0.9916409254074097,
   -0.9226894378662109,
   -0.9918196201324463,
   -0.9183297753334045,
   -0.9885678291320801,
   -0.93886798620224,
   -0.9663360714912415],
  'edit_count': 17},
 '2010-07-22': {'sentiments': [-0.9933270215988159], 'edit_count': 1},
 '2010-07-25': {'sentiments': [0.7879021763801575,
   -0.9949631690979004,
   0.7481208443641663,
   -0.7891218066215515],
  'edit_count': 4},
 '2010-07-29': {'sentiments': [0.9859933853149414,
   -0.9660219550132751,
   0.9931337833404541],
  'edit_count': 3},
 '2010-08-03': {'sentiments': [-0.9960501790046692,
   -0.991436779499054,
   -0.9846130609512329],
  'edit_count': 3},
 '2010-08-12': {'sentiments': [0.9703167080879211,
   0.9957578778266907,
   -0.7569971680641174,
   0.6267778277397156,
   0.6941722631454468,
   -0.8302779793739319,
   0.6403810977935791,
   -0.9994819760322571,
   0.9907135963439941],
  'edit_count': 9},
 '2010-08-14': {'sentiments': [-0.9994552731513977], 'edit_count': 1},
 '2010-08-18': {'sentiments': [-0.999642014503479], 'edit_count': 1},
 '2010-08-21': {'sentiments': [-0.9951968789100647], 'edit_count': 1},
 '2010-09-20': {'sentiments': [-0.9341223239898682], 'edit_count': 1},
 '2010-09-26': {'sentiments': [-0.9993003606796265, -0.9922304749488831],
  'edit_count': 2},
 '2010-09-27': {'sentiments': [-0.9997001886367798, -0.8906162977218628],
  'edit_count': 2},
 '2010-09-29': {'sentiments': [-0.9989383816719055], 'edit_count': 1},
 '2010-10-02': {'sentiments': [-0.915355920791626], 'edit_count': 1},
 '2010-10-05': {'sentiments': [-0.994151771068573], 'edit_count': 1},
 '2010-10-19': {'sentiments': [0.6267778277397156], 'edit_count': 1},
 '2010-11-10': {'sentiments': [0.9957578778266907], 'edit_count': 1},
 '2010-11-11': {'sentiments': [-0.9928996562957764], 'edit_count': 1},
 '2010-11-25': {'sentiments': [-0.9625310301780701], 'edit_count': 1},
 '2010-11-26': {'sentiments': [0.9957578778266907,
   -0.9824143052101135,
   -0.9042261242866516],
  'edit_count': 3},
 '2010-11-28': {'sentiments': [-0.9982038736343384], 'edit_count': 1},
 '2010-12-01': {'sentiments': [0.9957578778266907], 'edit_count': 1},
 '2010-12-05': {'sentiments': [0.7481208443641663,
   -0.9743338227272034,
   0.998600423336029],
  'edit_count': 3},
 '2010-12-10': {'sentiments': [0.7481208443641663,
   0.9957578778266907,
   0.7481208443641663,
   0.6554887294769287,
   0.9957578778266907,
   0.6554887294769287,
   0.9903573393821716,
   0.9952777624130249,
   0.5060251951217651,
   -0.9309778809547424,
   -0.8872181177139282,
   0.9953669309616089,
   -0.9937155842781067,
   0.9776464104652405,
   -0.999208390712738],
  'edit_count': 15},
 '2010-12-11': {'sentiments': [-0.985965371131897,
   0.8959269523620605,
   -0.9885092377662659,
   -0.9969037175178528,
   -0.9995896220207214,
   -0.9997856020927429,
   0.6554887294769287,
   0.9929860234260559,
   0.7481208443641663,
   -0.9690303802490234,
   0.7481208443641663,
   0.6554887294769287,
   0.6554887294769287,
   0.6554887294769287,
   0.6554887294769287,
   0.6554887294769287,
   0.7481208443641663,
   0.7481208443641663,
   0.7481208443641663,
   0.7481208443641663,
   0.7481208443641663,
   0.7481208443641663,
   0.7481208443641663,
   0.6267778277397156,
   0.7481208443641663,
   0.7481208443641663,
   0.6267778277397156,
   0.9408825039863586,
   0.9408825039863586,
   0.9408825039863586,
   0.9408825039863586,
   0.9408825039863586,
   0.9408825039863586,
   0.9408825039863586,
   0.9408825039863586,
   -0.9992044568061829,
   0.8337063193321228,
   0.7481208443641663,
   -0.9954670667648315,
   -0.9994016885757446,
   -0.9989022016525269,
   -0.9960851669311523,
   -0.9918407201766968,
   -0.9990273714065552,
   -0.983234167098999,
   0.9942771792411804,
   -0.9566611051559448,
   -0.9990301132202148,
   0.9408825039863586,
   0.9408825039863586],
  'edit_count': 50},
 '2010-12-12': {'sentiments': [-0.9911535382270813,
   -0.9347638487815857,
   -0.997890293598175,
   -0.9995604157447815,
   0.930020809173584,
   -0.991838276386261,
   0.6473709940910339,
   -0.9991673231124878,
   -0.9974265694618225,
   -0.9599932432174683,
   0.9430708885192871,
   -0.9954584836959839,
   0.7481208443641663,
   -0.9995869994163513,
   -0.9968892931938171,
   0.9408825039863586,
   0.9408825039863586],
  'edit_count': 17},
 '2010-12-13': {'sentiments': [-0.9909906387329102,
   0.9997393488883972,
   -0.9972816705703735,
   -0.9996923208236694,
   -0.9977468848228455,
   -0.9996894598007202,
   -0.9997749924659729,
   -0.9996359348297119,
   -0.9674910306930542,
   -0.9888002872467041,
   -0.9956533908843994,
   -0.9984694123268127],
  'edit_count': 12},
 '2010-12-14': {'sentiments': [-0.9916331768035889,
   -0.9970996379852295,
   -0.9944974780082703,
   0.8965078592300415,
   -0.9938361048698425,
   -0.700261652469635,
   -0.7377898097038269,
   -0.9997472167015076,
   -0.99974125623703,
   -0.9989713430404663,
   -0.9727956056594849,
   -0.9989645481109619,
   0.9945979118347168,
   0.9945979118347168,
   -0.6584357023239136,
   -0.992913544178009,
   -0.9013344645500183,
   0.9669950008392334,
   0.9932987093925476,
   -0.6776984930038452,
   -0.9165400266647339,
   -0.999135434627533,
   -0.9687707424163818,
   -0.9920401573181152,
   0.9652653932571411,
   -0.9578211307525635,
   0.997130811214447,
   -0.6263710260391235,
   -0.9934400916099548,
   -0.9997478127479553,
   -0.9989656209945679,
   -0.9013344645500183,
   -0.9948504567146301,
   -0.8260818123817444,
   -0.8260818123817444,
   -0.8273563981056213,
   -0.9960260391235352,
   -0.985582172870636,
   0.8748218417167664,
   0.7555941939353943,
   0.9408825039863586,
   0.9408825039863586,
   0.9408825039863586,
   -0.9911768436431885,
   0.7481208443641663,
   -0.9668503403663635,
   0.9324700832366943,
   0.537788987159729,
   -0.5387542247772217],
  'edit_count': 49},
 '2010-12-15': {'sentiments': [-0.9993361830711365,
   -0.999529242515564,
   -0.9997549653053284,
   -0.9638575911521912,
   0.9994445443153381,
   0.9965433478355408,
   0.9992485642433167,
   -0.9737254977226257,
   0.9997790455818176,
   0.9783644080162048,
   0.9921712875366211,
   -0.5683814883232117,
   0.8748218417167664,
   -0.9800392985343933,
   0.6554887294769287,
   -0.9967594742774963,
   -0.9838040471076965,
   -0.9859786629676819,
   -0.9954735636711121],
  'edit_count': 19},
 '2010-12-16': {'sentiments': [-0.9997054934501648,
   -0.997506320476532,
   -0.9990154504776001,
   -0.9868425726890564,
   -0.9592763781547546,
   -0.9978834986686707,
   -0.9989038705825806,
   0.9664132595062256,
   -0.9917243123054504,
   -0.9981663823127747,
   0.930020809173584],
  'edit_count': 11},
 '2010-12-17': {'sentiments': [-0.9683456420898438,
   -0.8241077661514282,
   -0.66774582862854,
   -0.8349349498748779],
  'edit_count': 4},
 '2010-12-18': {'sentiments': [-0.9997377991676331, -0.9993624091148376],
  'edit_count': 2},
 '2010-12-19': {'sentiments': [-0.9992154836654663,
   -0.9987003803253174,
   -0.6371783018112183,
   -0.5503098964691162,
   -0.9946306943893433],
  'edit_count': 5},
 '2010-12-20': {'sentiments': [0.9979097247123718,
   -0.992475688457489,
   -0.9378750920295715,
   -0.6118739247322083,
   0.9987550973892212,
   -0.9820846915245056,
   -0.9971206188201904,
   0.9175019860267639,
   -0.995936393737793,
   -0.9995241165161133,
   0.8748218417167664,
   -0.990691065788269,
   -0.9975748658180237,
   0.9612924456596375,
   0.7481208443641663,
   -0.9946526288986206,
   0.9246265888214111,
   0.6941722631454468,
   -0.9926360249519348,
   -0.9990752935409546,
   -0.9988248944282532,
   -0.9939500093460083],
  'edit_count': 22},
 '2010-12-21': {'sentiments': [-0.9935435056686401,
   0.9982189536094666,
   -0.9995046854019165,
   0.8661127090454102,
   0.8491294980049133,
   -0.9991501569747925,
   -0.9847477078437805,
   -0.9997418522834778,
   -0.9978615641593933,
   -0.9992679953575134,
   -0.9990087151527405,
   0.7209133505821228,
   -0.99835205078125,
   -0.9994219541549683,
   -0.9940019249916077,
   -0.9971189498901367,
   0.9764966368675232,
   0.8723396062850952,
   0.9071757793426514,
   0.7481208443641663,
   -0.9971189498901367,
   -0.9986202716827393,
   -0.9919557571411133,
   -0.9983444213867188,
   -0.999283492565155,
   -0.9994889497756958,
   0.7481208443641663],
  'edit_count': 27},
 '2010-12-22': {'sentiments': [0.6994761824607849,
   -0.9993208646774292,
   0.9945218563079834,
   -0.9948058724403381,
   -0.9991084933280945,
   -0.9932988882064819,
   -0.9918146729469299,
   -0.988599419593811,
   0.9587280750274658,
   -0.9975935816764832,
   0.931352972984314,
   -0.9868413209915161,
   0.9926673769950867,
   -0.9948333501815796,
   -0.9996185302734375,
   -0.9943406581878662,
   -0.988787829875946,
   -0.9953294992446899,
   0.9434965252876282,
   -0.9995242357254028,
   -0.9969195127487183,
   -0.9731929302215576,
   -0.9981561303138733,
   -0.9984764456748962,
   0.9670161604881287],
  'edit_count': 25},
 '2010-12-23': {'sentiments': [0.9408825039863586, 0.9408825039863586],
  'edit_count': 2},
 '2010-12-24': {'sentiments': [-0.9991777539253235], 'edit_count': 1},
 '2011-01-01': {'sentiments': [0.9105638861656189], 'edit_count': 1},
 '2011-01-06': {'sentiments': [-0.9996631145477295], 'edit_count': 1},
 '2011-01-07': {'sentiments': [-0.9908575415611267,
   0.7481208443641663,
   0.7481208443641663],
  'edit_count': 3},
 '2011-01-10': {'sentiments': [0.9672892689704895,
   -0.9928979873657227,
   -0.9899075031280518,
   0.7481208443641663],
  'edit_count': 4},
 '2011-01-11': {'sentiments': [-0.9997628331184387, -0.9990062117576599],
  'edit_count': 2},
 '2011-01-14': {'sentiments': [0.5266945958137512, -0.8840055465698242],
  'edit_count': 2},
 '2011-01-16': {'sentiments': [0.605577826499939,
   0.5908881425857544,
   -0.9220149517059326,
   -0.9960165619850159,
   -0.9980687499046326,
   0.7767417430877686,
   -0.9961167573928833,
   -0.9543552398681641,
   0.8009310960769653,
   -0.9271114468574524],
  'edit_count': 10},
 '2011-01-17': {'sentiments': [-0.9371862411499023,
   0.9975805282592773,
   -0.9752271175384521,
   -0.9964960217475891,
   -0.9992684721946716,
   0.8048130869865417,
   0.9957457184791565,
   0.5909348130226135],
  'edit_count': 8},
 '2011-01-20': {'sentiments': [-0.6644994020462036], 'edit_count': 1},
 '2011-01-21': {'sentiments': [0.9408825039863586,
   0.7481208443641663,
   0.7481208443641663,
   -0.9967197775840759,
   -0.9960933327674866,
   -0.9898148775100708],
  'edit_count': 6},
 '2011-01-22': {'sentiments': [-0.9456276297569275], 'edit_count': 1},
 '2011-01-24': {'sentiments': [0.7481208443641663,
   -0.9991505146026611,
   -0.9972015619277954,
   -0.6644994020462036],
  'edit_count': 4},
 '2011-01-25': {'sentiments': [-0.5590023398399353], 'edit_count': 1},
 '2011-01-26': {'sentiments': [-0.9716882705688477], 'edit_count': 1},
 '2011-01-29': {'sentiments': [-0.9884641766548157, -0.575320303440094],
  'edit_count': 2},
 '2011-01-31': {'sentiments': [-0.9942212104797363], 'edit_count': 1},
 '2011-02-01': {'sentiments': [-0.9900445938110352,
   -0.9997816681861877,
   -0.9982220530509949],
  'edit_count': 3},
 '2011-02-04': {'sentiments': [-0.9996967315673828], 'edit_count': 1},
 '2011-02-05': {'sentiments': [-0.998088538646698, -0.9911215305328369],
  'edit_count': 2},
 '2011-02-06': {'sentiments': [-0.9991208910942078,
   -0.9995949864387512,
   0.8335907459259033,
   -0.9936789870262146,
   -0.9967470169067383,
   -0.9996960163116455],
  'edit_count': 6},
 '2011-02-10': {'sentiments': [-0.9937098026275635,
   0.7663941979408264,
   -0.9951289892196655,
   -0.998580813407898,
   -0.9869794845581055,
   0.8827778697013855,
   0.6408429741859436,
   -0.9981383085250854],
  'edit_count': 8},
 '2011-02-11': {'sentiments': [-0.9964062571525574,
   0.5342882871627808,
   0.9179835319519043,
   -0.9985287189483643,
   0.930020809173584,
   0.930020809173584,
   0.930020809173584,
   0.930020809173584],
  'edit_count': 8},
 '2011-02-12': {'sentiments': [-0.9933351278305054,
   -0.9955112934112549,
   -0.6644994020462036,
   0.7481208443641663,
   -0.9855653643608093],
  'edit_count': 5},
 '2011-02-13': {'sentiments': [-0.8082680106163025, -0.7124696969985962],
  'edit_count': 2},
 '2011-02-14': {'sentiments': [-0.9961602687835693, -0.9976243376731873],
  'edit_count': 2},
 '2011-02-15': {'sentiments': [-0.9864668250083923,
   -0.9923012256622314,
   0.7481208443641663],
  'edit_count': 3},
 '2011-02-17': {'sentiments': [-0.9914788603782654,
   0.6554887294769287,
   -0.9930428266525269,
   0.9989898800849915],
  'edit_count': 4},
 '2011-02-18': {'sentiments': [-0.5806134343147278,
   -0.9996308088302612,
   -0.9975576400756836,
   -0.762265145778656],
  'edit_count': 4},
 '2011-02-20': {'sentiments': [-0.9961812496185303], 'edit_count': 1},
 '2011-02-23': {'sentiments': [0.6554887294769287,
   0.9977942705154419,
   -0.9939244389533997,
   -0.9996908903121948,
   0.80750972032547],
  'edit_count': 5},
 '2011-02-24': {'sentiments': [0.9833250045776367], 'edit_count': 1},
 '2011-02-25': {'sentiments': [-0.6478725075721741,
   -0.9954100251197815,
   -0.9692233800888062,
   -0.9915871620178223,
   0.7481208443641663],
  'edit_count': 5},
 '2011-02-26': {'sentiments': [0.9926506876945496, 0.7481208443641663],
  'edit_count': 2},
 '2011-02-28': {'sentiments': [0.9858648777008057, -0.580543041229248],
  'edit_count': 2},
 '2011-03-01': {'sentiments': [0.8048130869865417], 'edit_count': 1},
 '2011-03-04': {'sentiments': [0.7481208443641663, 0.9901989698410034],
  'edit_count': 2},
 '2011-03-07': {'sentiments': [0.7481208443641663,
   -0.999669075012207,
   0.9408825039863586,
   -0.9757394790649414,
   0.9949477910995483,
   -0.9339276552200317],
  'edit_count': 6},
 '2011-03-08': {'sentiments': [0.6523978114128113,
   -0.9976801872253418,
   -0.9992585778236389,
   -0.9997147917747498],
  'edit_count': 4},
 '2011-03-11': {'sentiments': [0.8737878203392029,
   -0.99665367603302,
   0.9949249029159546],
  'edit_count': 3},
 '2011-03-12': {'sentiments': [-0.9923986792564392], 'edit_count': 1},
 '2011-03-13': {'sentiments': [-0.6153927445411682], 'edit_count': 1},
 '2011-03-14': {'sentiments': [-0.9923911690711975, -0.998289167881012],
  'edit_count': 2},
 '2011-03-15': {'sentiments': [-0.9711605310440063], 'edit_count': 1},
 '2011-03-17': {'sentiments': [-0.9251040816307068], 'edit_count': 1},
 '2011-03-18': {'sentiments': [0.8889296054840088, -0.9892492294311523],
  'edit_count': 2},
 '2011-03-19': {'sentiments': [-0.9962666630744934], 'edit_count': 1},
 '2011-03-20': {'sentiments': [0.9894005656242371,
   -0.9992794394493103,
   -0.9809473156929016,
   -0.9753003716468811,
   -0.9964309930801392],
  'edit_count': 5},
 '2011-03-21': {'sentiments': [0.8048130869865417], 'edit_count': 1},
 '2011-03-22': {'sentiments': [0.8048130869865417], 'edit_count': 1},
 '2011-03-23': {'sentiments': [-0.9996017813682556,
   -0.9865647554397583,
   -0.9175481796264648,
   0.9408825039863586],
  'edit_count': 4},
 '2011-03-24': {'sentiments': [-0.9965630173683167], 'edit_count': 1},
 '2011-03-25': {'sentiments': [-0.9964498281478882,
   -0.9987818598747253,
   -0.73170006275177,
   0.7407240271568298,
   -0.9914788603782654,
   0.6554887294769287,
   -0.9849503040313721,
   0.6554887294769287],
  'edit_count': 8},
 '2011-03-26': {'sentiments': [0.7481208443641663,
   -0.9947303533554077,
   0.7481208443641663,
   -0.9980505704879761],
  'edit_count': 4},
 '2011-03-28': {'sentiments': [0.74684739112854,
   -0.9537158608436584,

In [10]:
from statistics import mean

for keys in edits:
  if len(edits[keys]['sentiments'])> 0:
    edits[keys]['mean_sentiments'] = mean(edits[keys]['sentiments'])
    edits[keys]["neg_sentiments"] = len([s for s in edits[keys]['sentiments'] if s < 0]) / len(edits[keys]['sentiments'])
    edits[keys]["pos_sentiments"] = len([s for s in edits[keys]['sentiments'] if s > 0]) / len(edits[keys]['sentiments'])

  else:
    edits[keys]['mean_sentiments'] = 0
    edits[keys]['neg_sentiments'] = 0
    edits[keys]['pos_sentiments'] = 0
  del edits[keys]['sentiments']
edits

{'2009-03-08': {'edit_count': 4,
  'mean_sentiments': -0.5505250692367554,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2009-08-05': {'edit_count': 1,
  'mean_sentiments': 0.7481208443641663,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2009-08-06': {'edit_count': 2,
  'mean_sentiments': 0.9957457184791565,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2009-08-14': {'edit_count': 1,
  'mean_sentiments': 0.930020809173584,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2009-10-13': {'edit_count': 2,
  'mean_sentiments': -0.22750061750411987,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2009-11-18': {'edit_count': 1,
  'mean_sentiments': 0.8839507699012756,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2009-12-08': {'edit_count': 1,
  'mean_sentiments': -0.9869275689125061,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2009-12-17': {'edit_count': 1,
  'mean_sentiments': -0.9975171089172363,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-02-23': {'edit_count': 1,
  'mean_sentiments': -0.9994946718215942,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-03-18': {'edit_count': 1,
  'mean_sentiments': 0.875877320766449,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-04-13': {'edit_count': 4,
  'mean_sentiments': 0.8443557024002075,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-04-15': {'edit_count': 8,
  'mean_sentiments': 0.5781013742089272,
  'neg_sentiments': 0.125,
  'pos_sentiments': 0.875},
 '2010-04-28': {'edit_count': 2,
  'mean_sentiments': -0.1209430992603302,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2010-05-13': {'edit_count': 1,
  'mean_sentiments': -0.9664837121963501,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-06-17': {'edit_count': 2,
  'mean_sentiments': 0.9957457184791565,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-06-18': {'edit_count': 9,
  'mean_sentiments': 0.35891877942615086,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2010-06-19': {'edit_count': 1,
  'mean_sentiments': 0.9875591397285461,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-06-20': {'edit_count': 3,
  'mean_sentiments': 0.9683796962102255,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-06-21': {'edit_count': 7,
  'mean_sentiments': 0.6157867397580828,
  'neg_sentiments': 0.14285714285714285,
  'pos_sentiments': 0.8571428571428571},
 '2010-06-23': {'edit_count': 4,
  'mean_sentiments': 0.8549632281064987,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-06-28': {'edit_count': 4,
  'mean_sentiments': 0.28316405415534973,
  'neg_sentiments': 0.25,
  'pos_sentiments': 0.75},
 '2010-06-29': {'edit_count': 1,
  'mean_sentiments': 0.7481208443641663,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-07-05': {'edit_count': 1,
  'mean_sentiments': 0.9360668659210205,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-07-07': {'edit_count': 2,
  'mean_sentiments': -0.15275686979293823,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2010-07-08': {'edit_count': 2,
  'mean_sentiments': 0.019024938344955444,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2010-07-09': {'edit_count': 1,
  'mean_sentiments': -0.9049850702285767,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-07-11': {'edit_count': 13,
  'mean_sentiments': 0.3211618891129127,
  'neg_sentiments': 0.3076923076923077,
  'pos_sentiments': 0.6923076923076923},
 '2010-07-12': {'edit_count': 9,
  'mean_sentiments': -0.2877997424867418,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2010-07-13': {'edit_count': 4,
  'mean_sentiments': 0.8065185099840164,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-07-14': {'edit_count': 4,
  'mean_sentiments': -0.06081320345401764,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2010-07-15': {'edit_count': 4,
  'mean_sentiments': -0.8949348777532578,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-07-16': {'edit_count': 6,
  'mean_sentiments': 0.9474905033906301,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-07-18': {'edit_count': 2,
  'mean_sentiments': -0.19054347276687622,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2010-07-19': {'edit_count': 4,
  'mean_sentiments': 0.8687809556722641,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-07-21': {'edit_count': 17,
  'mean_sentiments': -0.5357090515248916,
  'neg_sentiments': 0.7647058823529411,
  'pos_sentiments': 0.23529411764705882},
 '2010-07-22': {'edit_count': 1,
  'mean_sentiments': -0.9933270215988159,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-07-25': {'edit_count': 4,
  'mean_sentiments': -0.06201548874378204,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2010-07-29': {'edit_count': 3,
  'mean_sentiments': 0.3377017378807068,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2010-08-03': {'edit_count': 3,
  'mean_sentiments': -0.9907000064849854,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-08-12': {'edit_count': 9,
  'mean_sentiments': 0.2590402497185601,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2010-08-14': {'edit_count': 1,
  'mean_sentiments': -0.9994552731513977,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-08-18': {'edit_count': 1,
  'mean_sentiments': -0.999642014503479,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-08-21': {'edit_count': 1,
  'mean_sentiments': -0.9951968789100647,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-09-20': {'edit_count': 1,
  'mean_sentiments': -0.9341223239898682,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-09-26': {'edit_count': 2,
  'mean_sentiments': -0.9957654178142548,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-09-27': {'edit_count': 2,
  'mean_sentiments': -0.9451582431793213,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-09-29': {'edit_count': 1,
  'mean_sentiments': -0.9989383816719055,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-10-02': {'edit_count': 1,
  'mean_sentiments': -0.915355920791626,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-10-05': {'edit_count': 1,
  'mean_sentiments': -0.994151771068573,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-10-19': {'edit_count': 1,
  'mean_sentiments': 0.6267778277397156,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-11-10': {'edit_count': 1,
  'mean_sentiments': 0.9957578778266907,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-11-11': {'edit_count': 1,
  'mean_sentiments': -0.9928996562957764,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-11-25': {'edit_count': 1,
  'mean_sentiments': -0.9625310301780701,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-11-26': {'edit_count': 3,
  'mean_sentiments': -0.29696085055669147,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2010-11-28': {'edit_count': 1,
  'mean_sentiments': -0.9982038736343384,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-12-01': {'edit_count': 1,
  'mean_sentiments': 0.9957578778266907,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-12-05': {'edit_count': 3,
  'mean_sentiments': 0.257462481657664,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2010-12-10': {'edit_count': 15,
  'mean_sentiments': 0.3634859045346578,
  'neg_sentiments': 0.26666666666666666,
  'pos_sentiments': 0.7333333333333333},
 '2010-12-11': {'edit_count': 50,
  'mean_sentiments': 0.22862043380737304,
  'neg_sentiments': 0.32,
  'pos_sentiments': 0.68},
 '2010-12-12': {'edit_count': 17,
  'mean_sentiments': -0.336081161218531,
  'neg_sentiments': 0.6470588235294118,
  'pos_sentiments': 0.35294117647058826},
 '2010-12-13': {'edit_count': 12,
  'mean_sentiments': -0.8279572228590647,
  'neg_sentiments': 0.9166666666666666,
  'pos_sentiments': 0.08333333333333333},
 '2010-12-14': {'edit_count': 49,
  'mean_sentiments': -0.35597570575013454,
  'neg_sentiments': 0.6938775510204082,
  'pos_sentiments': 0.30612244897959184},
 '2010-12-15': {'edit_count': 19,
  'mean_sentiments': -0.15530411820662648,
  'neg_sentiments': 0.5789473684210527,
  'pos_sentiments': 0.42105263157894735},
 '2010-12-16': {'edit_count': 11,
  'mean_sentiments': -0.6393263827670704,
  'neg_sentiments': 0.8181818181818182,
  'pos_sentiments': 0.18181818181818182},
 '2010-12-17': {'edit_count': 4,
  'mean_sentiments': -0.8237835466861725,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-12-18': {'edit_count': 2,
  'mean_sentiments': -0.9995501041412354,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-12-19': {'edit_count': 5,
  'mean_sentiments': -0.8360069513320922,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2010-12-20': {'edit_count': 22,
  'mean_sentiments': -0.28941338712518866,
  'neg_sentiments': 0.6363636363636364,
  'pos_sentiments': 0.36363636363636365},
 '2010-12-21': {'edit_count': 27,
  'mean_sentiments': -0.3799964697272689,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2010-12-22': {'edit_count': 25,
  'mean_sentiments': -0.4561321234703064,
  'neg_sentiments': 0.72,
  'pos_sentiments': 0.28},
 '2010-12-23': {'edit_count': 2,
  'mean_sentiments': 0.9408825039863586,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2010-12-24': {'edit_count': 1,
  'mean_sentiments': -0.9991777539253235,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-01': {'edit_count': 1,
  'mean_sentiments': 0.9105638861656189,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-01-06': {'edit_count': 1,
  'mean_sentiments': -0.9996631145477295,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-07': {'edit_count': 3,
  'mean_sentiments': 0.1684613823890686,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2011-01-10': {'edit_count': 4,
  'mean_sentiments': -0.06684884428977966,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-01-11': {'edit_count': 2,
  'mean_sentiments': -0.9993845224380493,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-14': {'edit_count': 2,
  'mean_sentiments': -0.1786554753780365,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-01-16': {'edit_count': 10,
  'mean_sentiments': -0.30195448994636537,
  'neg_sentiments': 0.6,
  'pos_sentiments': 0.4},
 '2011-01-17': {'edit_count': 8,
  'mean_sentiments': -0.06488796323537827,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-01-20': {'edit_count': 1,
  'mean_sentiments': -0.6644994020462036,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-21': {'edit_count': 6,
  'mean_sentiments': -0.09091729919115703,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-01-22': {'edit_count': 1,
  'mean_sentiments': -0.9456276297569275,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-24': {'edit_count': 4,
  'mean_sentiments': -0.4781826585531235,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2011-01-25': {'edit_count': 1,
  'mean_sentiments': -0.5590023398399353,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-26': {'edit_count': 1,
  'mean_sentiments': -0.9716882705688477,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-29': {'edit_count': 2,
  'mean_sentiments': -0.7818922400474548,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-01-31': {'edit_count': 1,
  'mean_sentiments': -0.9942212104797363,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-01': {'edit_count': 3,
  'mean_sentiments': -0.9960161050160726,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-04': {'edit_count': 1,
  'mean_sentiments': -0.9996967315673828,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-05': {'edit_count': 2,
  'mean_sentiments': -0.9946050345897675,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-06': {'edit_count': 6,
  'mean_sentiments': -0.6925411919752756,
  'neg_sentiments': 0.8333333333333334,
  'pos_sentiments': 0.16666666666666666},
 '2011-02-10': {'edit_count': 8,
  'mean_sentiments': -0.3353152945637703,
  'neg_sentiments': 0.625,
  'pos_sentiments': 0.375},
 '2011-02-11': {'edit_count': 8,
  'mean_sentiments': 0.3971775099635124,
  'neg_sentiments': 0.25,
  'pos_sentiments': 0.75},
 '2011-02-12': {'edit_count': 5,
  'mean_sentiments': -0.5781580686569214,
  'neg_sentiments': 0.8,
  'pos_sentiments': 0.2},
 '2011-02-13': {'edit_count': 2,
  'mean_sentiments': -0.7603688538074493,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-14': {'edit_count': 2,
  'mean_sentiments': -0.9968923032283783,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-15': {'edit_count': 3,
  'mean_sentiments': -0.41021573543548584,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2011-02-17': {'edit_count': 4,
  'mean_sentiments': -0.08251076936721802,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-02-18': {'edit_count': 4,
  'mean_sentiments': -0.8350167572498322,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-20': {'edit_count': 1,
  'mean_sentiments': -0.9961812496185303,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-02-23': {'edit_count': 5,
  'mean_sentiments': 0.09343547821044922,
  'neg_sentiments': 0.4,
  'pos_sentiments': 0.6},
 '2011-02-24': {'edit_count': 1,
  'mean_sentiments': 0.9833250045776367,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-02-25': {'edit_count': 5,
  'mean_sentiments': -0.5711944460868835,
  'neg_sentiments': 0.8,
  'pos_sentiments': 0.2},
 '2011-02-26': {'edit_count': 2,
  'mean_sentiments': 0.8703857660293579,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-02-28': {'edit_count': 2,
  'mean_sentiments': 0.2026609182357788,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-03-01': {'edit_count': 1,
  'mean_sentiments': 0.8048130869865417,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-03-04': {'edit_count': 2,
  'mean_sentiments': 0.8691599071025848,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-03-07': {'edit_count': 6,
  'mean_sentiments': -0.03756417830785116,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-03-08': {'edit_count': 4,
  'mean_sentiments': -0.5860639363527298,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2011-03-11': {'edit_count': 3,
  'mean_sentiments': 0.29068634907404584,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2011-03-12': {'edit_count': 1,
  'mean_sentiments': -0.9923986792564392,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-03-13': {'edit_count': 1,
  'mean_sentiments': -0.6153927445411682,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-03-14': {'edit_count': 2,
  'mean_sentiments': -0.9953401684761047,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-03-15': {'edit_count': 1,
  'mean_sentiments': -0.9711605310440063,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-03-17': {'edit_count': 1,
  'mean_sentiments': -0.9251040816307068,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-03-18': {'edit_count': 2,
  'mean_sentiments': -0.05015981197357178,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-03-19': {'edit_count': 1,
  'mean_sentiments': -0.9962666630744934,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-03-20': {'edit_count': 5,
  'mean_sentiments': -0.592511510848999,
  'neg_sentiments': 0.8,
  'pos_sentiments': 0.2},
 '2011-03-21': {'edit_count': 1,
  'mean_sentiments': 0.8048130869865417,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-03-22': {'edit_count': 1,
  'mean_sentiments': 0.8048130869865417,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-03-23': {'edit_count': 4,
  'mean_sentiments': -0.49070805311203003,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2011-03-24': {'edit_count': 1,
  'mean_sentiments': -0.9965630173683167,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-03-25': {'edit_count': 8,
  'mean_sentiments': -0.3314574286341667,
  'neg_sentiments': 0.625,
  'pos_sentiments': 0.375},
 '2011-03-26': {'edit_count': 4,
  'mean_sentiments': -0.12413480877876282,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-03-28': {'edit_count': 3,
  'mean_sentiments': -0.39786213636398315,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2011-03-29': {'edit_count': 5,
  'mean_sentiments': -0.21896153688430786,
  'neg_sentiments': 0.6,
  'pos_sentiments': 0.4},
 '2011-03-30': {'edit_count': 1,
  'mean_sentiments': 0.8153420090675354,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-04-02': {'edit_count': 4,
  'mean_sentiments': -0.5029854029417038,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2011-04-04': {'edit_count': 4,
  'mean_sentiments': 0.3119431883096695,
  'neg_sentiments': 0.25,
  'pos_sentiments': 0.75},
 '2011-04-05': {'edit_count': 1,
  'mean_sentiments': -0.9985226988792419,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-04-06': {'edit_count': 7,
  'mean_sentiments': 0.3393149035317557,
  'neg_sentiments': 0.2857142857142857,
  'pos_sentiments': 0.7142857142857143},
 '2011-04-09': {'edit_count': 2,
  'mean_sentiments': 0.009099960327148438,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-04-11': {'edit_count': 5,
  'mean_sentiments': -0.25824403762817383,
  'neg_sentiments': 0.6,
  'pos_sentiments': 0.4},
 '2011-04-12': {'edit_count': 10,
  'mean_sentiments': 0.27081126570701597,
  'neg_sentiments': 0.3,
  'pos_sentiments': 0.7},
 '2011-04-13': {'edit_count': 5,
  'mean_sentiments': -0.640259063243866,
  'neg_sentiments': 0.8,
  'pos_sentiments': 0.2},
 '2011-04-14': {'edit_count': 7,
  'mean_sentiments': -0.4999725307737078,
  'neg_sentiments': 0.7142857142857143,
  'pos_sentiments': 0.2857142857142857},
 '2011-04-16': {'edit_count': 13,
  'mean_sentiments': -0.30793370650364804,
  'neg_sentiments': 0.6153846153846154,
  'pos_sentiments': 0.38461538461538464},
 '2011-04-17': {'edit_count': 2,
  'mean_sentiments': 0.9950544536113739,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-04-18': {'edit_count': 2,
  'mean_sentiments': -0.9971082508563995,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-04-19': {'edit_count': 8,
  'mean_sentiments': -0.4924311861395836,
  'neg_sentiments': 0.75,
  'pos_sentiments': 0.25},
 '2011-04-20': {'edit_count': 3,
  'mean_sentiments': -0.9985311031341553,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-04-21': {'edit_count': 2,
  'mean_sentiments': -0.12399932742118835,
  'neg_sentiments': 0.5,
  'pos_sentiments': 0.5},
 '2011-04-22': {'edit_count': 3,
  'mean_sentiments': 0.28150580326716107,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2011-04-24': {'edit_count': 1,
  'mean_sentiments': 0.6554887294769287,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-04-25': {'edit_count': 1,
  'mean_sentiments': -0.995245635509491,
  'neg_sentiments': 1.0,
  'pos_sentiments': 0.0},
 '2011-04-26': {'edit_count': 3,
  'mean_sentiments': 0.286892831325531,
  'neg_sentiments': 0.3333333333333333,
  'pos_sentiments': 0.6666666666666666},
 '2011-04-27': {'edit_count': 8,
  'mean_sentiments': -0.30213136225938797,
  'neg_sentiments': 0.625,
  'pos_sentiments': 0.375},
 '2011-04-28': {'edit_count': 3,
  'mean_sentiments': -0.3573858340581258,
  'neg_sentiments': 0.6666666666666666,
  'pos_sentiments': 0.3333333333333333},
 '2011-04-29': {'edit_count': 5,
  'mean_sentiments': 0.10088963508605957,
  'neg_sentiments': 0.4,
  'pos_sentiments': 0.6},
 '2011-04-30': {'edit_count': 1,
  'mean_sentiments': 0.990734338760376,
  'neg_sentiments': 0.0,
  'pos_sentiments': 1.0},
 '2011-05-02': {'edit_count': 5,
  'mean_sentiments': -0.22274833917617798,

In [11]:
# Creating a DataFrame from a dictionary.
import pandas as pd

edits_df = pd.DataFrame.from_dict(edits,orient ='index')
edits_df

            edit_count  mean_sentiments  neg_sentiments  pos_sentiments
2009-03-08           4        -0.550525            0.75            0.25
2009-08-05           1         0.748121            0.00            1.00
2009-08-06           2         0.995746            0.00            1.00
2009-08-14           1         0.930021            0.00            1.00
2009-10-13           2        -0.227501            0.50            0.50
...                ...              ...             ...             ...
2025-03-10           1         0.964989            0.00            1.00
2025-03-11           1        -0.857484            1.00            0.00
2025-03-12           1        -0.996866            1.00            0.00
2025-03-13           2        -0.996552            1.00            0.00
2025-03-19           1        -0.969953            1.00            0.00

[2758 rows x 4 columns]

```
orient="index" in Pandas
In Pandas, the orient="index" parameter is used when converting a dictionary to a DataFrame using pd.DataFrame.from_dict().

This tells Pandas that the keys of the dictionary should become the row labels (index) of the DataFrame instead of column labels.
```

In [12]:
# Converts the index (dates) to a proper datetime format for time-based operations.
edits_df.index = pd.to_datetime(edits_df.index)
edits_df

            edit_count  mean_sentiments  neg_sentiments  pos_sentiments
2009-03-08           4        -0.550525            0.75            0.25
2009-08-05           1         0.748121            0.00            1.00
2009-08-06           2         0.995746            0.00            1.00
2009-08-14           1         0.930021            0.00            1.00
2009-10-13           2        -0.227501            0.50            0.50
...                ...              ...             ...             ...
2025-03-10           1         0.964989            0.00            1.00
2025-03-11           1        -0.857484            1.00            0.00
2025-03-12           1        -0.996866            1.00            0.00
2025-03-13           2        -0.996552            1.00            0.00
2025-03-19           1        -0.969953            1.00            0.00

[2758 rows x 4 columns]

In [13]:
from datetime import datetime
date = pd.date_range(start='2009-03-08',end=datetime.today())
edits_df = edits_df.reindex(date,fill_value=0)
edits_df

            edit_count  mean_sentiments  neg_sentiments  pos_sentiments
2009-03-08           4        -0.550525            0.75            0.25
2009-03-09           0         0.000000            0.00            0.00
2009-03-10           0         0.000000            0.00            0.00
2009-03-11           0         0.000000            0.00            0.00
2009-03-12           0         0.000000            0.00            0.00
...                ...              ...             ...             ...
2025-03-27           0         0.000000            0.00            0.00
2025-03-28           0         0.000000            0.00            0.00
2025-03-29           0         0.000000            0.00            0.00
2025-03-30           0         0.000000            0.00            0.00
2025-03-31           0         0.000000            0.00            0.00

[5868 rows x 4 columns]

In [14]:
# Compute 30-Day Rolling Average
rolling_edits = edits_df.rolling(30, min_periods=30).mean()
rolling_edits = rolling_edits.dropna()
rolling_edits

            edit_count  mean_sentiments  neg_sentiments  pos_sentiments
2009-04-06    0.133333        -0.018351           0.025        0.008333
2009-04-07    0.000000         0.000000           0.000        0.000000
2009-04-08    0.000000         0.000000           0.000        0.000000
2009-04-09    0.000000         0.000000           0.000        0.000000
2009-04-10    0.000000         0.000000           0.000        0.000000
...                ...              ...             ...             ...
2025-03-27    0.300000        -0.161421           0.200        0.033333
2025-03-28    0.300000        -0.161421           0.200        0.033333
2025-03-29    0.300000        -0.161421           0.200        0.033333
2025-03-30    0.300000        -0.161421           0.200        0.033333
2025-03-31    0.300000        -0.161421           0.200        0.033333

[5839 rows x 4 columns]

In [15]:
rolling_edits.to_csv("btc_sent_roll.csv")